#namespace
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: containiq
spec: {}
status: {}
---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containiq
  namespace: containiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containiq
  template:
    spec:
      containers:
        - name: containiq
          image: "containiq/containiq"
          env:
            - name: NOTIFICATION_FILE_LOCATION
              value: /containiq/notification-config.yaml
          volumeMounts:
            - name: containiqconfig
              mountPath: /containiq
      serviceAccountName: containiq-sa
      volumes:
        - name: containiqconfig
          projected:
            sources:
              - secret:
                  name: containiq-notification
    metadata:
      labels:
        app: containiq
---
#service account
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: containiq-sa
  namespace: containiq
---
#clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: containiq
rules:
  - apiGroups: ["", "metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get","watch","list"]

---
#clusterrolebinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: containiq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: containiq
subjects:
  - kind: ServiceAccount
    namespace: containiq
    name: containiq-sa
---
#notification secret
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: containiq-notification
  namespace: containiq
stringData:
  notification-config.yaml: |
      Key: <CONTAINIQ_API_KEY>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: latency-controller
  namespace: containiq
  labels:
    app: latency-controller
spec:
  selector:
    matchLabels:
      name: latency-controller
  template:
    metadata:
      labels:
        name: latency-controller
    spec:
      containers:
        - name: containiq-latency-controller
          imagePullPolicy: Always
          image: containiq/latency-controller:latest
          env:
            - name: NOTIFICATION_FILE_LOCATION
              value: /containiq/notification-config.yaml
            - name: API_URL
              value: https://api.containiq.com/ingest/latency
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
          volumeMounts:
            - name: containiqconfig
              mountPath: /containiq
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
            - name: debug
              mountPath: /sys/kernel/debug
              readOnly: false
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: init-headers
          image: containiq/linux-headers
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN","NET_ADMIN"]
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
      serviceAccountName: containiq-sa
      volumes:
        - name: lsb-release
          hostPath:
            path: /etc/lsb-release
        - name: os-release
          hostPath:
            path: /etc/os-release
        - name: modules-dir
          hostPath:
            path: /var/cache/linux-headers/modules_dir
        - name: linux-headers-generated
          hostPath:
            path: /var/cache/linux-headers/generated
        - name: boot-host
          hostPath:
            path: /boot
        - name: modules-host
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
        - name: containiqconfig
          projected:
            sources:
              - secret:
                  name: containiq-notification


