apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "containiq.fullname" . }}-clusterrole
rules:
  - apiGroups:
      - ""
    resources: ["*"]
    verbs: ["get","watch","list"]
