#secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "containiq.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  notification-config.yaml: |
    {{- with .Values.comm }}
          {{- toYaml . | nindent 4 }}
    {{- end}}