#configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "containiq.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- with .Values.configuration }}
        {{- toYaml . | nindent 4 }}
    {{- end}}