#service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "containiq.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containiq.labels" . | nindent 4 }}
      {{- with .Values.serviceAccount.annotations }}
      annotations:
        {{- toYaml . | nindent 4 }}
      {{- end }}

